package vm

import (
	"bytes"
	"context"
	"crypto/rand"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"text/template"
)

const limaConfigTmpl = `# Auto-generated by mother
{{- if .BaseImage}}
images:
  - location: "{{.BaseImage}}"
    arch: "{{.Arch}}"
{{- else}}
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"
{{- end}}

cpus: 2
memory: "4GiB"
disk: "20GiB"

mounts:
  - location: "{{.ProjectDir}}"
    writable: true
  - location: "{{.ClaudeDir}}"
    writable: false
{{- if .SecretsFile}}
  - location: "{{.SecretsFile}}"
    writable: false
{{- end}}

{{- if .EnvVars}}
env:
{{- range .EnvVars}}
  {{.Key}}: "{{.Value}}"
{{- end}}
{{- end}}

provision:
{{- if not .BaseImage}}
  - mode: system
    script: |
      #!/bin/bash
      set -eux
      apt-get update
      apt-get install -y tmux
      curl -fsSL https://claude.ai/install.sh | bash
      find /root/.claude/bin /root/.local/bin -name claude -type f 2>/dev/null | head -1 | xargs -I{} cp {} /usr/local/bin/claude
      chmod +x /usr/local/bin/claude
{{- end}}
{{- if .SecretsFile}}
  - mode: system
    script: |
      #!/bin/bash
      set -eux
      cat > /etc/profile.d/mother-secrets.sh << 'PROFILE'
      if [ -f "{{.SecretsFile}}" ]; then
        set -a
        . "{{.SecretsFile}}"
        set +a
      fi
      PROFILE
      chmod 644 /etc/profile.d/mother-secrets.sh
{{- end}}
  - mode: user
    script: |
      #!/bin/bash
      set -eux
      cp -r "{{.ClaudeDir}}" "$HOME/.claude"
      if [ -f "{{.ClaudeDir}}/.coder-tmp/claude.json" ]; then
        cp "{{.ClaudeDir}}/.coder-tmp/claude.json" "$HOME/.claude.json"
      fi
`

type envEntry struct {
	Key   string
	Value string
}

type configData struct {
	ProjectDir  string
	ClaudeDir   string
	HomeDir     string
	SecretsFile string
	EnvVars     []envEntry
	BaseImage   string
	Arch        string
}

// Config holds the parameters needed to create a VM.
type Config struct {
	ProjectDir  string
	ClaudeDir   string
	HomeDir     string
	SecretsFile string
	EnvVars     map[string]string
}

// VM manages a Lima virtual machine instance.
type VM struct {
	Name   string
	config Config
}

// New creates a new VM manager with the given configuration.
func New(cfg Config) *VM {
	return &VM{
		Name:   randomName(),
		config: cfg,
	}
}

// GenerateConfig builds a Lima YAML config string.
func (v *VM) GenerateConfig() (string, error) {
	var entries []envEntry
	for k, val := range v.config.EnvVars {
		entries = append(entries, envEntry{k, val})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Key < entries[j].Key })

	tmpl, err := template.New("lima").Parse(limaConfigTmpl)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	baseImage, arch := baseImagePath()

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, configData{
		ProjectDir:  v.config.ProjectDir,
		ClaudeDir:   v.config.ClaudeDir,
		HomeDir:     v.config.HomeDir,
		SecretsFile: v.config.SecretsFile,
		EnvVars:     entries,
		BaseImage:   baseImage,
		Arch:        arch,
	}); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}

	return buf.String(), nil
}

// baseImagePath returns the path to a pre-built base image and the Lima arch
// string, or empty strings if no base image is available.
func baseImagePath() (string, string) {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return "", ""
	}

	var archLabel, limaArch string
	switch runtime.GOARCH {
	case "arm64":
		archLabel = "arm64"
		limaArch = "aarch64"
	case "amd64":
		archLabel = "amd64"
		limaArch = "x86_64"
	default:
		return "", ""
	}

	path := filepath.Join(homeDir, ".cache", "mother", "base-image-"+archLabel+".qcow2")
	if _, err := os.Stat(path); err != nil {
		return "", ""
	}

	fmt.Printf("Using base image: %s\n", path)
	return path, limaArch
}

// Start creates and starts the Lima VM.
func (v *VM) Start(ctx context.Context) error {
	config, err := v.GenerateConfig()
	if err != nil {
		return err
	}

	tmpFile, err := os.CreateTemp("", "coder-lima-*.yaml")
	if err != nil {
		return fmt.Errorf("creating temp file: %w", err)
	}
	defer os.Remove(tmpFile.Name())

	if _, err := tmpFile.WriteString(config); err != nil {
		tmpFile.Close()
		return fmt.Errorf("writing config: %w", err)
	}
	tmpFile.Close()

	fmt.Printf("Starting VM %s...\n", v.Name)

	cmd := exec.CommandContext(ctx, "limactl", "start", "--tty=false", "--name", v.Name, tmpFile.Name())
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("limactl start: %w", err)
	}

	return nil
}

// RunCommand executes a script inside the VM and returns captured stdout.
func (v *VM) RunCommand(ctx context.Context, workdir string, script string) (string, error) {
	tmpDir := filepath.Join(v.config.HomeDir, ".claude", ".coder-tmp")
	if err := os.MkdirAll(tmpDir, 0700); err != nil {
		return "", fmt.Errorf("creating temp dir: %w", err)
	}

	scriptFile := filepath.Join(tmpDir, "run.sh")
	if err := os.WriteFile(scriptFile, []byte(script), 0700); err != nil {
		return "", fmt.Errorf("writing run script: %w", err)
	}
	defer os.Remove(scriptFile)

	args := []string{"shell", "--workdir", workdir, v.Name, "bash", scriptFile}
	cmd := exec.CommandContext(ctx, "limactl", args...)

	var output bytes.Buffer
	cmd.Stdout = io.MultiWriter(os.Stdout, &output)
	cmd.Stderr = os.Stderr

	err := cmd.Run()
	return output.String(), err
}

// Cleanup force-deletes the Lima VM instance and removes any secrets tmpfile.
func (v *VM) Cleanup() {
	fmt.Printf("\nCleaning up VM %s...\n", v.Name)
	cmd := exec.Command("limactl", "delete", "--force", v.Name)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Run()

	if v.config.SecretsFile != "" {
		os.Remove(v.config.SecretsFile)
	}
}

// randomName returns a VM instance name like "coder-a1b2c3d4".
func randomName() string {
	b := make([]byte, 4)
	rand.Read(b)
	return fmt.Sprintf("coder-%x", b)
}
