package main

import (
	"bytes"
	"crypto/rand"
	"fmt"
	"io"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"sort"
	"strings"
	"syscall"
	"text/template"
)

const limaConfigTmpl = `# Auto-generated by coder
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"

cpus: 2
memory: "4GiB"
disk: "20GiB"

mounts:
  - location: "{{.ProjectDir}}"
    writable: true
  - location: "{{.ClaudeDir}}"
    writable: false

{{- if .EnvVars}}
env:
{{- range .EnvVars}}
  {{.Key}}: "{{.Value}}"
{{- end}}
{{- end}}

provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eux
      curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
      apt-get install -y nodejs
      npm install -g @anthropic-ai/claude-code
  - mode: user
    script: |
      #!/bin/bash
      set -eux
      cp -r "{{.ClaudeDir}}" "$HOME/.claude"
      if [ -f "{{.ClaudeDir}}/.coder-tmp/claude.json" ]; then
        cp "{{.ClaudeDir}}/.coder-tmp/claude.json" "$HOME/.claude.json"
      fi
`

type envEntry struct {
	Key   string
	Value string
}

type configData struct {
	ProjectDir string
	ClaudeDir  string
	HomeDir    string
	EnvVars    []envEntry
}

// GenerateConfig builds a Lima YAML config for the given project dir and env vars.
func GenerateConfig(projectDir, claudeDir, homeDir string, envMap map[string]string) (string, error) {
	// Sort keys for deterministic output
	var entries []envEntry
	for k, v := range envMap {
		entries = append(entries, envEntry{k, v})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Key < entries[j].Key })

	tmpl, err := template.New("lima").Parse(limaConfigTmpl)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, configData{
		ProjectDir: projectDir,
		ClaudeDir:  claudeDir,
		HomeDir:    homeDir,
		EnvVars:    entries,
	}); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}

	return buf.String(), nil
}

// randomSuffix returns a short random hex string.
func randomSuffix() string {
	b := make([]byte, 4)
	rand.Read(b)
	return fmt.Sprintf("%x", b)
}

// Start creates and starts a Lima VM, returning the instance name.
func Start(projectDir, claudeDir, homeDir string, envMap map[string]string) (string, error) {
	config, err := GenerateConfig(projectDir, claudeDir, homeDir, envMap)
	if err != nil {
		return "", err
	}

	tmpFile, err := os.CreateTemp("", "coder-lima-*.yaml")
	if err != nil {
		return "", fmt.Errorf("creating temp file: %w", err)
	}
	defer os.Remove(tmpFile.Name())

	if _, err := tmpFile.WriteString(config); err != nil {
		tmpFile.Close()
		return "", fmt.Errorf("writing config: %w", err)
	}
	tmpFile.Close()

	instance := "coder-" + randomSuffix()
	fmt.Printf("Starting VM %s...\n", instance)

	cmd := exec.Command("limactl", "start", "--tty=false", "--name", instance, tmpFile.Name())
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return instance, fmt.Errorf("limactl start: %w", err)
	}

	return instance, nil
}

// RunClaude executes Claude Code inside the VM and returns captured stdout.
func RunClaude(instance, projectDir, homeDir, prompt, systemPrompt, model string) (string, error) {
	// Write prompts to host temp files inside the mounted home dir so they're
	// visible in the VM via Lima's file sharing (no SSH stdin piping needed).
	tmpDir := filepath.Join(homeDir, ".claude", ".coder-tmp")
	if err := os.MkdirAll(tmpDir, 0700); err != nil {
		return "", fmt.Errorf("creating temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	// Build a shell script that claude will run.
	var script strings.Builder
	script.WriteString("#!/bin/bash\nset -e\nclaude --dangerously-skip-permissions")

	fullSystemPrompt := BuildSystemPrompt(systemPrompt)
	spFile := filepath.Join(tmpDir, "system-prompt.txt")
	if err := os.WriteFile(spFile, []byte(fullSystemPrompt), 0600); err != nil {
		return "", fmt.Errorf("writing system prompt: %w", err)
	}
	script.WriteString(fmt.Sprintf(` --append-system-prompt "$(cat '%s')"`, spFile))
	if model != "" {
		script.WriteString(" --model " + model)
	}
	if prompt != "" {
		pFile := filepath.Join(tmpDir, "prompt.txt")
		if err := os.WriteFile(pFile, []byte(prompt), 0600); err != nil {
			return "", fmt.Errorf("writing prompt: %w", err)
		}
		script.WriteString(fmt.Sprintf(` -p "$(cat '%s')"`, pFile))
	}
	script.WriteString("\n")

	scriptFile := filepath.Join(tmpDir, "run.sh")
	if err := os.WriteFile(scriptFile, []byte(script.String()), 0700); err != nil {
		return "", fmt.Errorf("writing run script: %w", err)
	}

	args := []string{"shell", "--workdir", projectDir, instance, "bash", scriptFile}

	cmd := exec.Command("limactl", args...)
	if prompt == "" {
		cmd.Stdin = os.Stdin // interactive mode needs terminal input
	}

	var output bytes.Buffer
	cmd.Stdout = io.MultiWriter(os.Stdout, &output)
	cmd.Stderr = os.Stderr

	err := cmd.Run()
	return output.String(), err
}

// Cleanup force-deletes the Lima VM instance.
func Cleanup(instance string) {
	fmt.Printf("\nCleaning up VM %s...\n", instance)
	cmd := exec.Command("limactl", "delete", "--force", instance)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Run()
}

// setupCleanup registers signal handlers so the VM is cleaned up on interrupt.
func setupCleanup(instance string) {
	ch := make(chan os.Signal, 1)
	signal.Notify(ch, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-ch
		Cleanup(instance)
		os.Exit(1)
	}()
}
