//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateJobRequestService.
const (
	Coder CreateJobRequestService = "coder"
)

// Valid indicates whether the value is a known member of the CreateJobRequestService enum.
func (e CreateJobRequestService) Valid() bool {
	switch e {
	case Coder:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	Completed JobStatus = "completed"
	Failed    JobStatus = "failed"
	Pending   JobStatus = "pending"
	Running   JobStatus = "running"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// CoderParams defines model for CoderParams.
type CoderParams struct {
	// EnvVars Environment variables to pass to the coder VM.
	EnvVars *map[string]string `json:"env_vars,omitempty"`

	// Model Model override (e.g., sonnet, opus).
	Model *string `json:"model,omitempty"`

	// ProjectDir Absolute path to the project directory.
	ProjectDir string `json:"project_dir"`

	// Prompt The prompt to send to Claude Code.
	Prompt string `json:"prompt"`

	// SystemPrompt System prompt override for Claude Code.
	SystemPrompt *string `json:"system_prompt,omitempty"`
}

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	Params CoderParams `json:"params"`

	// Service The service to invoke.
	Service CreateJobRequestService `json:"service"`
}

// CreateJobRequestService The service to invoke.
type CreateJobRequestService string

// CreateJobResponse defines model for CreateJobResponse.
type CreateJobResponse struct {
	// Id Unique job identifier.
	Id openapi_types.UUID `json:"id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Human-readable error message.
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Job defines model for Job.
type Job struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`

	// Error Error message, available when status is failed.
	Error  *string            `json:"error,omitempty"`
	Id     openapi_types.UUID `json:"id"`
	Params *CoderParams       `json:"params,omitempty"`

	// Result Output from the job, available when status is completed.
	Result  *string   `json:"result,omitempty"`
	Service string    `json:"service"`
	Status  JobStatus `json:"status"`
}

// JobStatus defines model for Job.Status.
type JobStatus string

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit a new job
	// (POST /api/v1/jobs)
	CreateJob(w http.ResponseWriter, r *http.Request)
	// Get job status and result
	// (GET /api/v1/jobs/{id})
	GetJob(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateJob operation middleware
func (siw *ServerInterfaceWrapper) CreateJob(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/v1/jobs", wrapper.CreateJob)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/jobs/{id}", wrapper.GetJob)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.HealthCheck)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xXTW8bNxD9KwO2hxbYrJSPQ6BbqhiOjRo13LSX2DCo5chLmUvSw9k1BEP/vSApyZJ3",
	"FaVF0pNWIjnz5s2bt9STqFzjnUXLQUyeRKhqbGR6nDqFdClJNumrJ+eRWGP6hra77SSlZ6mUZu2sNJd7",
	"e3jpUUxEYNL2TqwKoTBUpH3cKybixHaanG3QMnSStJwZDMAOvAzpk2uEKoKAvy9KUWziudkCK47xGqfQ",
	"xEz7gS/iz+A6JNIK4Rcs78oCgrMWuQDn2/DrTrhneJ5cjHyrNPWDfpgFZ1pG8JLrDbr1CVCasGJHy0Nx",
	"G8/9kJ9zhMZzjBfQqvg5NbJVCJH9wWhhGRib20NB/0zLm7hbEuaOjkReFYLwodWESky+7JGxLeFmoAlT",
	"Qsl47mZX+NBi4L5W/FZDPxPOxUT8NHoW3WituNGu3GKZSJ2ucJi19WKkS9vO3ad60LZNRJ4kswP1QIGb",
	"BMUG35Hignc2YL86rfoY/7L6oUVYuBlohZb1XCNFjHNHjWQxEW2r1dEeaDUI6oTI0WFAGJf7mD61jbSv",
	"CKWKgwZpFzQYgrz7BjnkoENoPqE0XB+GE1hyu/aM3CB3/w3dyaeGEp67WT9LFJRBRnUrkwK3RCvJ+Ip1",
	"g0OzVKX2/rszB+g92eWzANlJbRLRjzVayOWADjCX2qAanOyspCMSKf7bOBGG1gzYxR8t+5ZhTq5JjrZw",
	"s6+A37I87EzPI9tf66nAo1VxsRDUWpuftvHjqCSijislkfQ8zOtEe73tqygG0Xbu+oRM0TJJAx8uz5LN",
	"ICXvvHBcI5XwUQcvuaoxAGW/C9m8U/6QeNFsML2G4hGYOsvkDFwaaSPADinkVOPydTmO5DiPVnotJuJt",
	"OS7fJkviOrE1kl6PutejhZtlL3VhoIvZpgJIsPgIMixtFTtZwrQlQstmCc6aJYTWe0cRco1wnZ3yWmzQ",
	"l9f2CrklG0A3DSotGc0SHjXXIJOZnX0s4dIZA6cnn2EX2uhJq1UiKvNfXluR6iIZIZ6pLcg4vbmBGPg3",
	"p5Z5ei2jTYVJ742u0qnRIsTqNpeSo4p/+SJa7UuFqcU8CcmpEp1vxm9+RP61FyYA+506dzOQVYU+inxV",
	"iHfj8XcDsP9eGEh+ZjtptNooN41SaJtG0jLeHNpZo3mtoYWbpeVekyOIOxzQ4BUyaewwi6vKwlvLoQBp",
	"Y9roQaDnWx8pkmSStsqeXk6Rs1iS4SFjvG1+eRI6ZosDIgphZRNHLXnAfqeLHdKOvXVveqr4fk05T0QO",
	"6kAhS21ClsG7/08GMbd1DHPXWvVCBKfIadLXnv/ctqyGOr3sv6aBZB9r48y7N5bQa3C+OUxrrO7FD+zA",
	"iwvKACF5x/IFFflXqBK+dCqXlVW4H+F3V0kDCjs0zqd/NHmvKERLRkxEzewno5GJ+2oXePJ+/H4sVjer",
	"fwIAAP//MsisJYENAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
